# Generated by Django 5.0.4 on 2024-05-03 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre_Collecte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=31)),
                ('adresse', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=31)),
                ('prenom', models.CharField(max_length=31)),
                ('date_naissance', models.DateTimeField()),
                ('groupe_sanguin', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=31)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receveur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=31)),
                ('prenom', models.CharField(max_length=31)),
                ('date_naissance', models.DateField()),
                ('groupe_sanguin', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Sang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_sang', models.CharField(max_length=31)),
                ('quantite', models.IntegerField()),
                ('date_reception', models.DateField()),
                ('date_expiration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_don', models.DateTimeField()),
                ('quantite', models.IntegerField()),
                ('collecte', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='collecte.centre_collecte')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('donneur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collecte.donneur')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel_Medical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialite', models.CharField(max_length=40)),
                ('collecte', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='collecte.centre_collecte')),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfusion',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantite', models.IntegerField()),
                ('receveur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collecte.receveur')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collecte.stock_sang')),
            ],
        ),
    ]
