# Generated by Django 5.0.4 on 2024-05-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0002_stock_sang_don_alter_don_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='quantite',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
